### ISSUE TITLE
Returning fetch_news() as list, dic or json.

### ISSUE THREAD

**Issue by Frank-py** [HubertJan/itspylearning#1]
As mentioned in the title, I'd like to suggest returning a list, dictionary or json, instead of an unsubscriptable object in the function called "fetch_news".

**Comment by HubertJan** [comment]
"fetch_news" itself does return a list, but all of its elements are unsubscriptable because they are objects of the news data class.
I chose that approach, because it is easier to understand, what attributes a news object contains. If I'd be using a dictionary, it wouldn't be obvious what entries it had (without separate documentation). 
But if you need a subscribable object, you could add a to_json function to the data class, that converts it to a json string.
